[build]
  base = "/"
  command = """
    bash scripts/deploy-checks.sh && \
    echo "🚀 Starting deployment..." && \
    npm install && \
    npm run build
  """
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"
  CI = "true"
  NODE_ENV = "production"
  DEBUG = "*"

[build.processing]
  skip_processing = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 8080
  publish = "dist"

# Add build plugins for error tracking
[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[plugins]]
  package = "@netlify/plugin-sitemap"

[[plugins]]
  package = "@sentry/netlify-build-plugin"

[plugins.inputs]
  sentryOrg = "your-org"
  sentryProject = "your-project"

# Add deploy notifications
[[plugins]]
  package = "netlify-plugin-discord"

[plugins.inputs]
  webhookUrl = "your-discord-webhook"

# Add health checks
[[plugins]]
  package = "netlify-plugin-checklinks"

[plugins.inputs]
  skipPatterns = [
    "#",
    "mailto:",
    "tel:"
  ]

# Add performance monitoring
[[plugins]]
  package = "netlify-plugin-submit-sitemap"

# Add error pages
[[redirects]]
  from = "/404"
  to = "/404.html"
  status = 404

[context.production.environment]
  VITE_APP_ENV = "production"

[context.deploy-preview.environment]
  VITE_APP_ENV = "preview"
