[build]
  command = """
    npm cache clean --force && \
    rm -rf node_modules && \
    npm install && \
    npm run build
  """
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"
  CI = "true"
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 8080
  publish = "dist"
