[build]
  command = """
    npm ci && \
    rm -rf dist && \
    npm run build
  """
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-audit --no-fund"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 8080
  publish = "dist"
