[build]
  base = "/"
  command = """
    echo "Node version: $(node --version)" && \
    echo "NPM version: $(npm --version)" && \
    echo "Current directory: $(pwd)" && \
    echo "Directory contents: $(ls -la)" && \
    echo "Installing dependencies..." && \
    npm install --verbose && \
    echo "Building application..." && \
    npm run build --verbose
  """
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"
  CI = "true"
  NODE_ENV = "production"
  DEBUG = "*"

[build.processing]
  skip_processing = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 8080
  publish = "dist"
